server:
  port: 8081

client:
  collaborator:
    name: api-collaborator

  project:
    name: api-project

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: api-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2